# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import galleries.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre de la Galerie')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Titre')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Légende')),
                ('alt_text', models.CharField(blank=True, max_length=125, null=True, verbose_name='Alternative Textuelle')),
                ('file', models.ImageField(max_length=200, upload_to=galleries.models.content_filename, verbose_name='Fichier')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Gallery')),
            ],
        ),
    ]
