# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import galleries.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_auto_20160802_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_small',
            field=models.ImageField(null=True, upload_to=galleries.models.content_filename_small),
        ),
        migrations.AddField(
            model_name='photo',
            name='file_thumbnail',
            field=models.ImageField(null=True, upload_to=galleries.models.content_filename_thumbnail),
        ),
    ]
